FROM metasploitframework/metasploit-framework:latest

USER root

# Remplacer le miroir APK par un miroir officiel stable
RUN sed -i 's|dl-cdn.alpinelinux.org|dl-4.alpinelinux.org|g' /etc/apk/repositories && \
    apk update && apk add --no-cache \
    python3 \
    py3-pip \
    postgresql-client \
    bash

RUN pip install xmltodict

WORKDIR /app

COPY msf_auto_scan.py /app/msf_auto_scan.py
COPY metasploit/scan_template.rc /app/metasploit/scan_template.rc

CMD ["/bin/bash", "-c", "msfconsole -r /app/metasploit/scan_template.rc"]
