version: '3.8'

services:
  nmapscanner:
    build:
      context: ./nmap
      dockerfile: Dockerfile
    container_name: nmapscanner
    volumes:
      - ./scanner.py:/app/nmapscan.py
      - ./results:/app/results
    working_dir: /app
    entrypoint: ["python3", "nmapscan.py"]
    networks:
      - secnet

networks:
  secnet:
    driver: bridge
