version: '3.8'

services:
  nmapscanner:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nmapscanner
    volumes:
      - ./scanner.py:/app/scanner.py
      - ./results:/app/results
    command: python3 /app/scanner.py 192.168.1.1
    networks:
      - secnet
      
volumes:
  pgdata:

networks:
  secnet:
    driver: bridge
